notifications:
  email:
    recipients:
      - yuzhiping140103@hotmail.com
    on_success: change
    on_failure: always

sudo: false
language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

install: true
script:
  - travis_wait 30 ./mvnw clean install -DskipTests=false

after_success:
  - bash <(curl -s https://codecov.io/bash)